const DB="ShowCueDB",VER=4;let db,state={sets:[],current:null,selected:null,library:{audio:[],video:[]}},editing=null,currentAudio=null,master=1,muted=false,objectUrls=[],tvOn=false,settings={padLayout:50,finishMode:"stop",theme:"dark",padSize:"big",defaultColor:"#a991d7",volumeSync:true};
const TARGET_LUFS=-16,$=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random(),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),ext=n=>(String(n).split(".").pop()||"").toLowerCase(),esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),fmtTime=s=>{s=Number.isFinite(s)?s:0;return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`};let lyricsAutoScroll=false,lyricsScrollRaf=0,lyricsLastTs=0;
function updateLyricsScrollUi(){const b=$("lyricsAutoScrollBtn"),m=$("lyricsManualScrollBtn"),stage=$("lyricsBody")?.closest('.lyricstage'),speed=$("lyricsScrollSpeed"),sv=$("lyricsScrollSpeedValue");if(b){b.classList.toggle('active',lyricsAutoScroll);b.textContent=lyricsAutoScroll?'⏸ Stop Auto Scroll':'▶ Auto Scroll'}if(m)m.classList.toggle('active',!lyricsAutoScroll);if(stage){stage.classList.toggle('auto-scroll',lyricsAutoScroll);stage.classList.toggle('manual-scroll',!lyricsAutoScroll)}if(speed&&sv)sv.textContent=speed.value}
function stopLyricsAutoScroll(){lyricsAutoScroll=false;if(lyricsScrollRaf)cancelAnimationFrame(lyricsScrollRaf);lyricsScrollRaf=0;lyricsLastTs=0;updateLyricsScrollUi()}
function runLyricsAutoScroll(ts){if(!lyricsAutoScroll)return;const stage=$("lyricsBody")?.closest('.lyricstage');if(!stage){stopLyricsAutoScroll();return}const body=$("lyricsBody");const max=Math.max(0,stage.scrollHeight-stage.clientHeight);if(max<=0){stopLyricsAutoScroll();return}const speed=Number($("lyricsScrollSpeed")?.value||5);
  // When a track is playing, map lyric position to the track timeline. Speed 5 is exact track sync; lower is slower, higher is faster.
  if(currentAudio && Number.isFinite(currentAudio.duration) && currentAudio.duration>0){
    const multiplier=speed/5;
    const progress=clamp((currentAudio.currentTime/currentAudio.duration)*multiplier,0,1);
    const target=max*progress;
    // Smoothly follow the track while correcting quickly enough to stay in sync.
    const blend=Math.min(1,0.12+speed*0.025);
    stage.scrollTop += (target-stage.scrollTop)*blend;
    if(currentAudio.ended || currentAudio.currentTime>=currentAudio.duration-0.05){stage.scrollTop=max;stopLyricsAutoScroll();return}
  }else{
    if(!lyricsLastTs)lyricsLastTs=ts;
    const dt=Math.min(100,ts-lyricsLastTs)/1000;lyricsLastTs=ts;
    const pxPerSec=18+speed*9;
    stage.scrollTop=Math.min(max,stage.scrollTop+pxPerSec*dt);
    if(stage.scrollTop>=max-1){stage.scrollTop=max;stopLyricsAutoScroll();return}
  }
  lyricsScrollRaf=requestAnimationFrame(runLyricsAutoScroll)}
function startLyricsAutoScroll(){const stage=$("lyricsBody")?.closest('.lyricstage');if(!stage)return;if(stage.scrollHeight<=stage.clientHeight){toast('There is not enough lyric text to scroll.');return}if(lyricsScrollRaf)cancelAnimationFrame(lyricsScrollRaf);lyricsAutoScroll=true;lyricsLastTs=0;updateLyricsScrollUi();lyricsScrollRaf=requestAnimationFrame(runLyricsAutoScroll)}
$("lyricsAutoScrollBtn").onclick=()=>lyricsAutoScroll?stopLyricsAutoScroll():startLyricsAutoScroll();$("lyricsManualScrollBtn").onclick=stopLyricsAutoScroll;$("lyricsScrollSpeed").oninput=()=>updateLyricsScrollUi();const lyricStage=$("lyricsBody")?.closest('.lyricstage');if(lyricStage){['touchstart','wheel','pointerdown'].forEach(ev=>lyricStage.addEventListener(ev,e=>{if(e.target.closest('.lyricScrollControls'))return;if(lyricsAutoScroll)stopLyricsAutoScroll()},{passive:true}));}updateLyricsScrollUi();
async function importLyricsFile(file){const p=selectedPad();if(!p){toast('Select a cue first.');return}try{let text='';const name=file.name||'';if(file.type==='application/pdf'||ext(name)==='pdf'){if(!window.pdfjsLib){await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.js';sc.onload=resolve;sc.onerror=reject;document.head.appendChild(sc)})}const pdfjs=window.pdfjsLib;if(!pdfjs)throw Error('PDF reader unavailable.');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.js';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();pages.push(content.items.map(x=>x.str).join(' '))}text=pages.join('\n\n')}else{text=await file.text();if(ext(name)==='rtf')text=text.replace(/\\[a-z]+\d* ?/gi,'').replace(/[{}]/g,'')}if(!text.trim())throw Error('No readable text found.');p.lyrics=text;p.lyricsFileName=name;await save();renderLyrics();toast('Lyrics imported to the selected cue.')}catch(e){console.error(e);toast('Could not read that lyrics file on this device. TXT/MD/RTF are supported locally; PDF uses the browser PDF reader.')}}
$('importLyricsBtn').onclick=()=>{const p=selectedPad();if(!p){toast('Select a cue first.');return}$('lyricsManualPanel').style.display='none';$('lyricsManualText').value=p.lyrics||'';$('lyricsPdfStatus').textContent='';$('lyricsImportModal').classList.add('open')};$('lyricsImportClose').onclick=()=>{$('lyricsImportModal').classList.remove('open')};$('lyricsManualBtn').onclick=()=>{$('lyricsPdfStatus').textContent='';$('lyricsManualPanel').style.display='block';$('lyricsManualText').focus()};$('lyricsManualCancel').onclick=()=>{$('lyricsManualPanel').style.display='none'};$('lyricsManualSave').onclick=async()=>{const p=selectedPad();if(!p)return;p.lyrics=$('lyricsManualText').value;p.lyricsFileName='Manual entry';await save();$('lyricsImportModal').classList.remove('open');renderLyrics();toast('Lyrics saved to the selected cue.')};$('lyricsPdfBtn').onclick=()=>{const p=selectedPad();if(!p){toast('Select a cue first.');return}$('lyricsPdfStatus').textContent='Select a PDF file…';$('lyricsPdfFile').click()};$('lyricsPdfFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;$('lyricsPdfStatus').textContent='Reading PDF…';await importLyricsFile(f);$('lyricsImportModal').classList.remove('open')};$('lyricsPlayBtn').onclick=()=>{const p=selectedPad();if(p){const el=[...document.querySelectorAll('.pad')].find(x=>x.dataset.id===p.id)||null;playPad(p,el)}};$('lyricsStopBtn').onclick=stopAll;
$('padLayout').onchange=async e=>{settings.padLayout=Number(e.target.value);const s=currentSet();while(s.pads.length<settings.padLayout&&s.pads.length<50)s.pads.push({id:uid(),name:"",color:settings.defaultColor,mode:"restart"});await save();render()};$('finishMode').onchange=async e=>{settings.finishMode=e.target.value;await save()};$('displayTheme').onchange=async e=>{settings.theme=e.target.value;applySettings();await save()};$('padSize').onchange=async e=>{settings.padSize=e.target.value;applySettings();await save();render()};
$('matchAll').onclick=async()=>{const s=currentSet();$('matchStatus').textContent='Matching tracks…';let n=0;for(const p of s.pads)if(p.audioBlob){p.gainDb=await analyse(p.audioBlob);n++}await save();$('matchStatus').textContent=`Matched ${n} track${n===1?'':'s'} for playback.`;toast('Volume sync complete.')};$('persistBtn').onclick=async()=>{if(navigator.storage?.persist){const ok=await navigator.storage.persist();$('storageStatus').textContent=ok?'Persistent storage requested.':'Browser did not grant persistent storage.'}};$('clearData').onclick=async()=>{if(confirm('Delete all ShowCue setlists and imported media from this browser?')){await put('sets',[]);await put('library',{audio:[],video:[]});location.reload()}};
$('importTrack').onclick=()=>{$('trackFiles').click();$('menuDrop').classList.remove('open')};$('trackFiles').onchange=async e=>{await importTracks(e.target.files);e.target.value=''};$('importVideo').onclick=()=>{$('videoFiles').click();$('menuDrop').classList.remove('open')};$('videoFiles').onchange=async e=>{await importVideos(e.target.files);e.target.value=''};$('closeLibrary').onclick=()=>$('libraryModal').classList.remove('open');$('manualBtn').onclick=()=>{$('manualModal').classList.add('open');$('menuDrop').classList.remove('open')};$('closeManual').onclick=()=>$('manualModal').classList.remove('open');
async function exportPlaylist(){const payload={app:'ShowCue',version:5,exported:new Date().toISOString(),settings,sets:[]};for(const s of state.sets){const ns={...s,pads:[]};for(const p of s.pads){const q={...p};if(p.audioBlob){const f=new File([p.audioBlob],p.audioName||'audio');q.audioData=await fileToData(f);delete q.audioBlob}if(p.videoBlob){const f=new File([p.videoBlob],p.videoName||'video');q.videoData=await fileToData(f);delete q.videoBlob}if(p.tvPhotoBlob){const f=new File([p.tvPhotoBlob],p.tvPhotoName||'photo');q.tvPhotoData=await fileToData(f);delete q.tvPhotoBlob}ns.pads.push(q)}payload.sets.push(ns)}const blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(currentSet()?.name||'ShowCue-Playlist')+'.showcue.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}async function importPlaylist(file){const txt=await file.text(),p=JSON.parse(txt);if(!p?.sets)throw Error('Invalid ShowCue playlist');for(const s of p.sets){for(const q of s.pads||[]){if(q.audioData)q.audioBlob=await dataToBlob(q.audioData);if(q.videoData)q.videoBlob=await dataToBlob(q.videoData);if(q.tvPhotoData)q.tvPhotoBlob=await dataToBlob(q.tvPhotoData);delete q.audioData;delete q.videoData;delete q.tvPhotoData}}state.sets=p.sets;settings=Object.assign(settings,p.settings||{});state.current=state.sets[0]?.id;await save();applySettings();render();renderSetlists();renderLyrics();toast('Playlist loaded.')}
$('exportPlaylist').onclick=()=>{exportPlaylist().catch(e=>toast('Could not export playlist.'));$('menuDrop').classList.remove('open')};$('loadPlaylist').onclick=()=>{$('playlistFile').click();$('menuDrop').classList.remove('open')};$('playlistFile').onchange=async e=>{if(e.target.files[0])try{await importPlaylist(e.target.files[0])}catch(err){toast('Invalid ShowCue playlist file.')}e.target.value=''};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});boot().catch(e=>{console.error(e);toast('ShowCue could not open its local database.')});
